name: Convert from MD to PDF and Upload

on: push

permissions:
  actions: read
  contents: read

jobs:
  convert:
    name: Convert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update apt
        run: sudo apt-get update
      - name: Install Pandoc
        run: sudo apt-get install pandoc pandoc-citeproc texlive-extra-utils texlive-fonts-recommended texlive-latex-base texlive-latex-extra texlive-bibtex-extra biber
      - name: Convert Markdown to PDF
        run: bash build.sh
      - name: Nest zip
        run: zip -r pdfs.zip ./pdfs
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: pdfs.zip
  upload: 
    name: Upload
    runs-on: ubuntu-latest
    needs: convert
    environment: deploy
    if: github.ref == 'refs/heads/deploy'
    steps:
      - name: Download PDFs
        uses: actions/download-artifact@v3
        with:
          name: pdfs
      - name: Unzip
        run: unzip pdfs.zip
      - name: Upload PDFs to tool
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTPHOST }}
          port: 22
          username: ${{ secrets.SFTPUSER }}
          password: ${{ secrets.SFTPPASSWORD }}
          localPath: ./pdfs
          remotePath: ./global-plastics-tool.org/pdf
