name: Convert from MD to PDF and Upload

on: push

permissions:
  actions: read
  contents: read

jobs:
  convert:
    name: Convert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Convert Markdown to PDF
        run: |
          mkdir pdfs/
          for file in *.md; do
            output_file="pdfs/$(basename $file .md).pdf"
            docker run --volume $PWD:/data pandoc/latex:2.9 --output=/data/$output_file /data/$file
          done
      - name: Nest zip
        run: zip -r pdfs.zip ./pdfs
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: pdfs.zip
  upload: 
    name: Upload
    runs-on: ubuntu-latest
    needs: convert
    environment: deploy
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download PDFs
        uses: actions/download-artifact@v3
        with:
          name: pdfs
      - name: Unzip
        run: unzip pdfs.zip
      - name: Upload PDFs to tool
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTPHOST }}
          port: 22
          username: ${{ secrets.SFTPUSER }}
          password: ${{ secrets.SFTPPASSWORD }}
          localPath: ./pdf
          remotePath: ./global-plastics-tool.org/pdf
